title: Resume - Rahul Raj
description:  Online Resume
url: https://randomwalk.in
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
