title: Personal Profile 
description:  Online CV
url: https://randomwalk.in
baseurl: 'rahulrajpl.github.io'
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
