# exampleSite/config.yaml
baseURL: https://rahulrajpl.github.io/ # Replace with your domain
languageCode: en-us
theme: smigle
themesDir: ../.. # Only needed for running the example site
title: Random Walk
menu:
  main: # Change menu as needed
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: Eexperience
      name: Experience
      url: /experience/
      weight: 3
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 4
    
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 5
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 6
    - identifier: rss
      name: RSS
      url: /index.xml
      weight: 7
params:
  abbrDateFmt: "Jan 2"
  author: "Rahul Raj"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"
  ##
  ## Options for overriding theme or page defaults
  ##
  #customStylesheets: # Use to override theme styles, like logo size
  #  - "css/custom.css"
  #readingSpeed: 600 # Use to set custom reading speed
  #readingSpeedMin: 25 # Use to set custom reading speed range
  #readingSpeedMax: 175 # Use to set custom reading speed range
  social:
    - name: GitHub
      url: https://github.com/rahulrajpl
    - name: LinkedIn
      url: https://www.linkedin.com/in/rahul-r-909409184/
    - name: Twitter
      url: https://twitter.com/rand0mwalker
    - name: StackOverflow
      url: https://stackoverflow.com/users/9981029/rahul
    - name: Instagram
      url: https://www.instagram.com/rand0mwalker/
  subtitle: "Personal website of Rahul Raj"
